<map id="NCollection_UBTree&lt; TheObjType, TheBndType &gt;::Selector" name="NCollection_UBTree&lt; TheObjType, TheBndType &gt;::Selector">
<area shape="rect" id="node2" href="$class_b_rep_builder_a_p_i___bnd_box_tree_selector.html" title="Class BRepBuilderAPI_BndBoxTreeSelector derived from UBTree::Selector This class is used to select ov..." alt="" coords="265,5,458,47"/>
<area shape="rect" id="node3" href="$class_b_rep_class3d___bnd_box_tree_selector_line.html" title="BRepClass3d_BndBoxTreeSelectorLine" alt="" coords="236,71,487,98"/>
<area shape="rect" id="node4" href="$class_b_rep_class3d___bnd_box_tree_selector_point.html" title="BRepClass3d_BndBoxTreeSelector\lPoint" alt="" coords="248,123,475,164"/>
<area shape="rect" id="node5" href="$class_shape_analysis___box_bnd_tree_selector.html" title="ShapeAnalysis_BoxBndTree\lSelector" alt="" coords="268,188,455,229"/>
</map>
